services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: logstash
    restart: unless-stopped

    volumes:
      - ./pipeline:/usr/share/logstash/pipeline:ro
      - ./pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro

    ports:
      - "5044:5044"
      - "514:514/udp"
      - "9600:9600"

    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
