services:
  logstash:
    image: logstash:9.2.4
    container_name: logstash
    restart: unless-stopped

    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml

    ports:
      - "5044:5044"
      - "9600:9600"

    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"

